// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAud0AbD_p74UlgppDzgSGP7Qh1E11iLqM',
    appId: '1:935455184326:web:7898f269f15c9c338b8ec7',
    messagingSenderId: '935455184326',
    projectId: 'progra-954f6',
    authDomain: 'progra-954f6.firebaseapp.com',
    storageBucket: 'progra-954f6.appspot.com',
    measurementId: 'G-LRKEYFZTYG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJOa0dWPIo-wlR62S6HApf2u2Nxnaxp3o',
    appId: '1:935455184326:android:8fff0a2fda7363fc8b8ec7',
    messagingSenderId: '935455184326',
    projectId: 'progra-954f6',
    storageBucket: 'progra-954f6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnYn76wUIFJ0_hpaUUNZoHVXjUYTWhH_M',
    appId: '1:935455184326:ios:eda2487985c8b0408b8ec7',
    messagingSenderId: '935455184326',
    projectId: 'progra-954f6',
    storageBucket: 'progra-954f6.appspot.com',
    iosBundleId: 'com.example.firebasestrems',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnYn76wUIFJ0_hpaUUNZoHVXjUYTWhH_M',
    appId: '1:935455184326:ios:e3e2b7639c7b74598b8ec7',
    messagingSenderId: '935455184326',
    projectId: 'progra-954f6',
    storageBucket: 'progra-954f6.appspot.com',
    iosBundleId: 'com.example.firebasestrems.RunnerTests',
  );
}
